# Generated by Django 3.0.3 on 2020-02-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200213_2015'),
        ('user', '0002_auto_20200213_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Movie'),
        ),
    ]
